### ISSUE TITLE
Bugs In site

### ISSUE THREAD

**Issue by himani-kansal** [Manan-YMCA/ElementsCulmyca2017Website#11]
1) Home and events are highligting simultaneously in navigation bar
2) In team page:- Check  Navigation content.
3) In register dialog box, Paytm transaction box is not shown after clicking on offline button.

**Comment by SidharthMehta** [comment]
1. Online publicity and prefest events Ismein publicity word hatao
2. Some events are free Pament ka option ni aana chahiye unmein
3. Contact info for event organisers
4. Scailing ka issue hai
5. Open any event See at top of page Text ec k upar aaraha hai
6.Formating of rules
7. Zoom of web site can be turned off
8. Team vale page pe jo pics hai vo as it is daal di hai As in unka aspect ratio 1:1 Nahi hai So it looks compressed/streched
9. Fb integration theek place pe nahi hai
10. Contact us mein insta snapchat youtube and fb page ka link daldo

**Comment by SidharthMehta** [comment]
10. Event categories vale section mein right vala button niche aaraha hai instead of same level

**Comment by vipinkhushu** [comment]
@himani-kansal 
Feedback on your bugs
1. Bug metioned in https://github.com/Manan-YMCA/ElementsCulmyca2017Website/issues/17
2. Fixed by @aakashverma12 https://github.com/Manan-YMCA/ElementsCulmyca2017Website/commit/08c54b0ac21bdb21891417e87cd6bdd82b368793
3. Bug filed in https://github.com/Manan-YMCA/ElementsCulmyca2017Website/issues/18

**Comment by vipinkhushu** [comment]
@SidharthMehta 
 Feedback on your bugs
1. Assigned to @aakashverma12 
2. We are removing all payment options https://github.com/Manan-YMCA/ElementsCulmyca2017Website/issues/18
3. Contact Mayank Nagpal from Brix Team for this, he will be handing this, he has the access to add this kind of info into the website
4. Assigned to @aakashverma12 on https://github.com/Manan-YMCA/ElementsCulmyca2017Website/issues/10
5. Assigned to @aakashverma12 on https://github.com/Manan-YMCA/ElementsCulmyca2017Website/issues/10
6. We cant do this, responsive issues.
7. Its because we were given pictures which were not 1:1 scaled, but we need to maintain uniformity, so we rescaled it. anyways if we somehow get 1:1 scaled pics of everone, we can update it anytime.
8. Fixed https://github.com/Manan-YMCA/ElementsCulmyca2017Website/commit/db1150503c75fff3bf0ebc028ed7ea022cd066af
9. Can you arrange list a list of all social profile links, we will add this.
10. Assigned to @aakashverma12

**Comment by vipinkhushu** [comment]
#11 Fixed including all subparts
